fun main() {
    throw Exception("ssss")
}